# No Chilli Chilli

A tame chilli that will delight lightweights and chilli-heads alike

This is a traditional beef chilli that does not contain chilli (pepper). What it lacks in heat it more than makes up for with a big punch of spicy flavour. Although it takes a while to cook the recipe is quite forgiving. As long as you get everything mostly right, you'll end up with something delicious. Serve with chilli sauce so any chilli heads can spice it up!

## Ingredients

**For the chilli; Serves 4-6 generously**

- vegetable oil
- 4cm cinnamon or cassia bark
- 2 bay leaves
- 3 large onions, finely diced
- bulb garlic
- 2 tbsp smoked paprika
- 1 tbsp ground cumin
- 1 tbsp ground coriander
- 2 tbsp dried oregano
- 2 tbsp tomato puree
- 750g lean beef mince
- 2 tins cherry tomatoes
- beef stock cube
- 25g dark chocolate (darker the better)
- 2 tbsp tomato ketchup
- double espresso
- tin black beans
- tin red kidney beans
- tin haricot beans
- 3 tbsp finely chopped coriander (leaf)

**To serve**

- Basmati or other long grain rice
- Greek yoghurt
- grated parmesan
- chilli sauce*

***optional**

## Method

**Total time 90 mins for prep and cooking**

1. Add a decent glug of oil to a wok, so it covers the bottom. Add cinnamon and bay leaves, heat for a couple of mins.
2. Add onions and cook down until brown, stirring regularly. The total cook time for onions will be 30-40 mins.
3. While the onions cook peel garlic cloves and crush to a paste with pestle and mortar. Add to onions as they are cooking.
4. Add paprika, cumin, coriander, oregano and tomato puree to onions. Cook out for 2-3 mins. There should be oil visible in the bottom of the pan. If the mix looks too dry, add a bit more oil.
5. Add beef mince, mix and fry until mostly browned.
6. Transfer mixture to large pan, add tinned tomatoes, stock cube, chocolate, ketchup, and espresso. Bring to boil. At this stage you may need to add additional water to loosen the sauce. Between 0 and half a (empty tinned tomato) can will do it. Simmer the chilli covered for anywhere between 30 to 60 mins, depending on your serving time. You can adjust consistency by adding more water or taking the lid off.

*If you are serving rice, now is a good time to put it on*

7. 20 mins before serving, drain, rinse and add the 3 tins of beans. Taste and adjust flavour with more ketchup, salt or sugar (the espresso can sometimes make it bitter, which needs balancing).
8. Five mins before serving, add the chopped coriander. Et voila!

Serve your chilli with rice, with a dollop of yoghurt, grated parmesan and a sprinkling of chopped coriander on top. And a gallon of chilli sauce, of course :)
